export const JSONData = [
  {
    "attributes":{
      "Opportunity_Number":1641984,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":76,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":13,
      "Total_Days_Identified_Through_Closing":104,
      "Total_Days_Identified_Through_Qualified":101,
      "Opportunity_Amount_USD":0,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":5,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.69636,
      "Ratio_Days_Validated_To_Total_Days":0.113985,
      "Ratio_Days_Qualified_To_Total_Days":0.154215,
      "Deal_Size_Category":1
    }
  },
  {
    "attributes":{
      "Opportunity_Number":1658010,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":63,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":2,
      "Total_Days_Identified_Through_Closing":163,
      "Total_Days_Identified_Through_Qualified":163,
      "Opportunity_Amount_USD":0,
      "Client_Size_By_Revenue":3,
      "Client_Size_By_Employee_Count":5,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":1,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":1
    }
  },
  {
    "attributes":{
      "Opportunity_Number":1674737,
      "Supplies_Subgroup":"Motorcycle Parts",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Pacific",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":24,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":7,
      "Total_Days_Identified_Through_Closing":82,
      "Total_Days_Identified_Through_Qualified":82,
      "Opportunity_Amount_USD":7750,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":1,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":1
    }
  },
  {
    "attributes":{
      "Opportunity_Number":1675224,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Midwest",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":16,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":5,
      "Total_Days_Identified_Through_Closing":124,
      "Total_Days_Identified_Through_Qualified":124,
      "Opportunity_Amount_USD":0,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":1,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":1
    }
  },
  {
    "attributes":{
      "Opportunity_Number":1689785,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":69,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":11,
      "Total_Days_Identified_Through_Closing":91,
      "Total_Days_Identified_Through_Qualified":13,
      "Opportunity_Amount_USD":69756,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.141125,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":1692390,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Pacific",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":89,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":3,
      "Total_Days_Identified_Through_Closing":114,
      "Total_Days_Identified_Through_Qualified":0,
      "Opportunity_Amount_USD":232522,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.000877,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":5
    }
  },
  {
    "attributes":{
      "Opportunity_Number":1935837,
      "Supplies_Subgroup":"Garage & Car Care",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":111,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":12,
      "Total_Days_Identified_Through_Closing":112,
      "Total_Days_Identified_Through_Qualified":112,
      "Opportunity_Amount_USD":20001,
      "Client_Size_By_Revenue":4,
      "Client_Size_By_Employee_Count":5,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.308863,
      "Ratio_Days_Validated_To_Total_Days":0.568487,
      "Ratio_Days_Qualified_To_Total_Days":0.12265,
      "Deal_Size_Category":2
    }
  },
  {
    "attributes":{
      "Opportunity_Number":1952571,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":82,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":6,
      "Total_Days_Identified_Through_Closing":70,
      "Total_Days_Identified_Through_Qualified":70,
      "Opportunity_Amount_USD":450000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":0.26361,
      "Ratio_Days_Validated_To_Total_Days":0.73639,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":6
    }
  },
  {
    "attributes":{
      "Opportunity_Number":1999486,
      "Supplies_Subgroup":"Batteries & Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":68,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":8,
      "Total_Days_Identified_Through_Closing":156,
      "Total_Days_Identified_Through_Qualified":156,
      "Opportunity_Amount_USD":250000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":5,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"None",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.562821,
      "Ratio_Days_Qualified_To_Total_Days":0.437179,
      "Deal_Size_Category":6
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2052337,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":18,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":7,
      "Total_Days_Identified_Through_Closing":50,
      "Total_Days_Identified_Through_Qualified":50,
      "Opportunity_Amount_USD":55003,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.585317,
      "Ratio_Days_Qualified_To_Total_Days":0.414683,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2100568,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":76,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":8,
      "Total_Days_Identified_Through_Closing":165,
      "Total_Days_Identified_Through_Qualified":165,
      "Opportunity_Amount_USD":0,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":2,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.417729,
      "Ratio_Days_Validated_To_Total_Days":0.23558,
      "Ratio_Days_Qualified_To_Total_Days":0.346691,
      "Deal_Size_Category":1
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2190367,
      "Supplies_Subgroup":"Garage & Car Care",
      "Supplies_Group":"Car Accessories",
      "Region":"Midwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":87,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":5,
      "Total_Days_Identified_Through_Closing":142,
      "Total_Days_Identified_Through_Qualified":142,
      "Opportunity_Amount_USD":400000,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":5,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":0.015482,
      "Ratio_Days_Validated_To_Total_Days":0.370162,
      "Ratio_Days_Qualified_To_Total_Days":0.614356,
      "Deal_Size_Category":6
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2217068,
      "Supplies_Subgroup":"Performance Parts",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Midwest",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":35,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":6,
      "Total_Days_Identified_Through_Closing":31,
      "Total_Days_Identified_Through_Qualified":31,
      "Opportunity_Amount_USD":10000,
      "Client_Size_By_Revenue":2,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.167213,
      "Ratio_Days_Qualified_To_Total_Days":0.832787,
      "Deal_Size_Category":2
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2223143,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":16,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":5,
      "Total_Days_Identified_Through_Closing":208,
      "Total_Days_Identified_Through_Qualified":208,
      "Opportunity_Amount_USD":232522,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.946076,
      "Ratio_Days_Validated_To_Total_Days":0.053924,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":5
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2228661,
      "Supplies_Subgroup":"Batteries & Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Midwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":81,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":10,
      "Total_Days_Identified_Through_Closing":138,
      "Total_Days_Identified_Through_Qualified":138,
      "Opportunity_Amount_USD":200000,
      "Client_Size_By_Revenue":4,
      "Client_Size_By_Employee_Count":5,
      "Revenue_From_Client_Past_Two_Years":4,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.730044,
      "Ratio_Days_Qualified_To_Total_Days":0.269956,
      "Deal_Size_Category":5
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2228983,
      "Supplies_Subgroup":"Batteries & Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":79,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":5,
      "Total_Days_Identified_Through_Closing":32,
      "Total_Days_Identified_Through_Qualified":32,
      "Opportunity_Amount_USD":0,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":0.024845,
      "Ratio_Days_Validated_To_Total_Days":0.456522,
      "Ratio_Days_Qualified_To_Total_Days":0.518634,
      "Deal_Size_Category":1
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2263363,
      "Supplies_Subgroup":"Towing & Hitches",
      "Supplies_Group":"Car Accessories",
      "Region":"Midwest",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":83,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":13,
      "Total_Days_Identified_Through_Closing":130,
      "Total_Days_Identified_Through_Qualified":130,
      "Opportunity_Amount_USD":60000,
      "Client_Size_By_Revenue":4,
      "Client_Size_By_Employee_Count":3,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.12182,
      "Ratio_Days_Validated_To_Total_Days":0.558982,
      "Ratio_Days_Qualified_To_Total_Days":0.319198,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2277276,
      "Supplies_Subgroup":"Garage & Car Care",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":65,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":17,
      "Total_Days_Identified_Through_Closing":150,
      "Total_Days_Identified_Through_Qualified":150,
      "Opportunity_Amount_USD":250009,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":5,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":0.068182,
      "Ratio_Days_Validated_To_Total_Days":0.625,
      "Ratio_Days_Qualified_To_Total_Days":0.306818,
      "Deal_Size_Category":6
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2280685,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":91,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":6,
      "Total_Days_Identified_Through_Closing":103,
      "Total_Days_Identified_Through_Qualified":103,
      "Opportunity_Amount_USD":500000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":3,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":1,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":7
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2284303,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":65,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":13,
      "Total_Days_Identified_Through_Closing":125,
      "Total_Days_Identified_Through_Qualified":125,
      "Opportunity_Amount_USD":100000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":5,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"None",
      "Ratio_Days_Identified_To_Total_Days":0.029695,
      "Ratio_Days_Validated_To_Total_Days":0.128411,
      "Ratio_Days_Qualified_To_Total_Days":0.841894,
      "Deal_Size_Category":5
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2289905,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Pacific",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":89,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":7,
      "Total_Days_Identified_Through_Closing":60,
      "Total_Days_Identified_Through_Qualified":60,
      "Opportunity_Amount_USD":150000,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":4,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.313433,
      "Ratio_Days_Validated_To_Total_Days":0.686567,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":5
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2292996,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Midwest",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":62,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":14,
      "Total_Days_Identified_Through_Closing":88,
      "Total_Days_Identified_Through_Qualified":87,
      "Opportunity_Amount_USD":210000,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":3,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.041096,
      "Ratio_Days_Validated_To_Total_Days":0.8379,
      "Ratio_Days_Qualified_To_Total_Days":0.11758,
      "Deal_Size_Category":5
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2296022,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Midwest",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":16,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":8,
      "Total_Days_Identified_Through_Closing":169,
      "Total_Days_Identified_Through_Qualified":169,
      "Opportunity_Amount_USD":3000,
      "Client_Size_By_Revenue":3,
      "Client_Size_By_Employee_Count":2,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.189125,
      "Ratio_Days_Validated_To_Total_Days":0.810875,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":1
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2315483,
      "Supplies_Subgroup":"Motorcycle Parts",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Midwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":83,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":7,
      "Total_Days_Identified_Through_Closing":90,
      "Total_Days_Identified_Through_Qualified":48,
      "Opportunity_Amount_USD":80000,
      "Client_Size_By_Revenue":3,
      "Client_Size_By_Employee_Count":5,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.403352,
      "Ratio_Days_Qualified_To_Total_Days":0.134078,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2315706,
      "Supplies_Subgroup":"Motorcycle Parts",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Northwest",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":73,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":9,
      "Total_Days_Identified_Through_Closing":127,
      "Total_Days_Identified_Through_Qualified":127,
      "Opportunity_Amount_USD":40721,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":1,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.403467,
      "Ratio_Days_Validated_To_Total_Days":0.43814,
      "Ratio_Days_Qualified_To_Total_Days":0.158392,
      "Deal_Size_Category":3
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2315732,
      "Supplies_Subgroup":"Motorcycle Parts",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Midwest",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":76,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":8,
      "Total_Days_Identified_Through_Closing":133,
      "Total_Days_Identified_Through_Qualified":133,
      "Opportunity_Amount_USD":64000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":4,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.141679,
      "Ratio_Days_Validated_To_Total_Days":0.344828,
      "Ratio_Days_Qualified_To_Total_Days":0.513493,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2345802,
      "Supplies_Subgroup":"Motorcycle Parts",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Midwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":86,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":2,
      "Total_Days_Identified_Through_Closing":119,
      "Total_Days_Identified_Through_Qualified":119,
      "Opportunity_Amount_USD":51000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":3,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":1,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":2368166,
      "Supplies_Subgroup":"Replacement Parts",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":60,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":8,
      "Total_Days_Identified_Through_Closing":101,
      "Total_Days_Identified_Through_Qualified":101,
      "Opportunity_Amount_USD":50000,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":3,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.740631,
      "Ratio_Days_Validated_To_Total_Days":0.089744,
      "Ratio_Days_Qualified_To_Total_Days":0.169625,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":3255657,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":72,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":9,
      "Total_Days_Identified_Through_Closing":123,
      "Total_Days_Identified_Through_Qualified":123,
      "Opportunity_Amount_USD":500000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":5,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"None",
      "Ratio_Days_Identified_To_Total_Days":0.381729,
      "Ratio_Days_Validated_To_Total_Days":0.401305,
      "Ratio_Days_Qualified_To_Total_Days":0.216966,
      "Deal_Size_Category":7
    }
  },
  {
    "attributes":{
      "Opportunity_Number":3256426,
      "Supplies_Subgroup":"Replacement Parts",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":44,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":4,
      "Total_Days_Identified_Through_Closing":9,
      "Total_Days_Identified_Through_Qualified":9,
      "Opportunity_Amount_USD":35812,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":3,
      "Revenue_From_Client_Past_Two_Years":2,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":1,
      "Deal_Size_Category":3
    }
  },
  {
    "attributes":{
      "Opportunity_Number":3258440,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":1,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":8,
      "Total_Days_Identified_Through_Closing":192,
      "Total_Days_Identified_Through_Qualified":192,
      "Opportunity_Amount_USD":109767,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":3,
      "Revenue_From_Client_Past_Two_Years":1,
      "Competitor_Type":"None",
      "Ratio_Days_Identified_To_Total_Days":0.087884,
      "Ratio_Days_Validated_To_Total_Days":0.861154,
      "Ratio_Days_Qualified_To_Total_Days":0.049922,
      "Deal_Size_Category":5
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4127586,
      "Supplies_Subgroup":"Batteries & Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":86,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":6,
      "Total_Days_Identified_Through_Closing":78,
      "Total_Days_Identified_Through_Qualified":78,
      "Opportunity_Amount_USD":400000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":5,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":0.02046,
      "Ratio_Days_Validated_To_Total_Days":0.148338,
      "Ratio_Days_Qualified_To_Total_Days":0.831202,
      "Deal_Size_Category":6
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4130619,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Midwest",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":49,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":2,
      "Total_Days_Identified_Through_Closing":149,
      "Total_Days_Identified_Through_Qualified":149,
      "Opportunity_Amount_USD":70000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":2,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":1,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4169974,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":138,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":4,
      "Total_Days_Identified_Through_Closing":59,
      "Total_Days_Identified_Through_Qualified":50,
      "Opportunity_Amount_USD":0,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":3,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.042159,
      "Ratio_Days_Qualified_To_Total_Days":0.79258,
      "Deal_Size_Category":1
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4270911,
      "Supplies_Subgroup":"Performance Parts",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Midwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":77,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":2,
      "Total_Days_Identified_Through_Closing":119,
      "Total_Days_Identified_Through_Qualified":119,
      "Opportunity_Amount_USD":566077,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"None",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":1,
      "Deal_Size_Category":7
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4299750,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Pacific",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":91,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":8,
      "Total_Days_Identified_Through_Closing":57,
      "Total_Days_Identified_Through_Qualified":57,
      "Opportunity_Amount_USD":201519,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":2,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":1,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":5
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4351439,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":91,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":6,
      "Total_Days_Identified_Through_Closing":97,
      "Total_Days_Identified_Through_Qualified":97,
      "Opportunity_Amount_USD":10000,
      "Client_Size_By_Revenue":3,
      "Client_Size_By_Employee_Count":2,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":1,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":2
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4362737,
      "Supplies_Subgroup":"Performance Parts",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Midwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":76,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":10,
      "Total_Days_Identified_Through_Closing":95,
      "Total_Days_Identified_Through_Qualified":95,
      "Opportunity_Amount_USD":134969,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":4,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.142558,
      "Ratio_Days_Qualified_To_Total_Days":0.857442,
      "Deal_Size_Category":5
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4478161,
      "Supplies_Subgroup":"Batteries & Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Midwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":77,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":6,
      "Total_Days_Identified_Through_Closing":111,
      "Total_Days_Identified_Through_Qualified":111,
      "Opportunity_Amount_USD":260000,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":4,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":0.147482,
      "Ratio_Days_Validated_To_Total_Days":0.742806,
      "Ratio_Days_Qualified_To_Total_Days":0.109712,
      "Deal_Size_Category":6
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4488903,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Midwest",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":45,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":8,
      "Total_Days_Identified_Through_Closing":128,
      "Total_Days_Identified_Through_Qualified":128,
      "Opportunity_Amount_USD":0,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":3,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.442533,
      "Ratio_Days_Validated_To_Total_Days":0.130571,
      "Ratio_Days_Qualified_To_Total_Days":0.426896,
      "Deal_Size_Category":1
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4495075,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Midwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":85,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":4,
      "Total_Days_Identified_Through_Closing":62,
      "Total_Days_Identified_Through_Qualified":62,
      "Opportunity_Amount_USD":75000,
      "Client_Size_By_Revenue":4,
      "Client_Size_By_Employee_Count":4,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.012987,
      "Ratio_Days_Validated_To_Total_Days":0.987013,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4538348,
      "Supplies_Subgroup":"Tires & Wheels",
      "Supplies_Group":"Tires & Wheels",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":54,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":8,
      "Total_Days_Identified_Through_Closing":128,
      "Total_Days_Identified_Through_Qualified":121,
      "Opportunity_Amount_USD":700000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.217018,
      "Ratio_Days_Validated_To_Total_Days":0.403591,
      "Ratio_Days_Qualified_To_Total_Days":0.320062,
      "Deal_Size_Category":7
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4548217,
      "Supplies_Subgroup":"Batteries & Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":84,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":8,
      "Total_Days_Identified_Through_Closing":40,
      "Total_Days_Identified_Through_Qualified":39,
      "Opportunity_Amount_USD":39373,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.6025,
      "Ratio_Days_Qualified_To_Total_Days":0.3675,
      "Deal_Size_Category":3
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4562313,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Midwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":78,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":4,
      "Total_Days_Identified_Through_Closing":35,
      "Total_Days_Identified_Through_Qualified":35,
      "Opportunity_Amount_USD":70000,
      "Client_Size_By_Revenue":3,
      "Client_Size_By_Employee_Count":3,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.259259,
      "Ratio_Days_Validated_To_Total_Days":0.740741,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4569449,
      "Supplies_Subgroup":"Batteries & Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":63,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":21,
      "Total_Days_Identified_Through_Closing":31,
      "Total_Days_Identified_Through_Qualified":31,
      "Opportunity_Amount_USD":10000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":4,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.022876,
      "Ratio_Days_Qualified_To_Total_Days":0.977124,
      "Deal_Size_Category":2
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4569795,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":84,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":6,
      "Total_Days_Identified_Through_Closing":98,
      "Total_Days_Identified_Through_Qualified":98,
      "Opportunity_Amount_USD":210843,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":2,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":0.182564,
      "Ratio_Days_Validated_To_Total_Days":0.289231,
      "Ratio_Days_Qualified_To_Total_Days":0.528205,
      "Deal_Size_Category":5
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4569954,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":24,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":9,
      "Total_Days_Identified_Through_Closing":61,
      "Total_Days_Identified_Through_Qualified":48,
      "Opportunity_Amount_USD":63000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":3,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.398693,
      "Ratio_Days_Validated_To_Total_Days":0.01634,
      "Ratio_Days_Qualified_To_Total_Days":0.362745,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4574254,
      "Supplies_Subgroup":"Replacement Parts",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":74,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":8,
      "Total_Days_Identified_Through_Closing":108,
      "Total_Days_Identified_Through_Qualified":105,
      "Opportunity_Amount_USD":46504,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":2,
      "Revenue_From_Client_Past_Two_Years":2,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.123491,
      "Ratio_Days_Qualified_To_Total_Days":0.847725,
      "Deal_Size_Category":3
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4574291,
      "Supplies_Subgroup":"Replacement Parts",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":24,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":5,
      "Total_Days_Identified_Through_Closing":64,
      "Total_Days_Identified_Through_Qualified":64,
      "Opportunity_Amount_USD":67431,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":2,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":1,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4604833,
      "Supplies_Subgroup":"Performance Parts",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Midwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":89,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":8,
      "Total_Days_Identified_Through_Closing":93,
      "Total_Days_Identified_Through_Qualified":93,
      "Opportunity_Amount_USD":73619,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.190065,
      "Ratio_Days_Qualified_To_Total_Days":0.809935,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4605197,
      "Supplies_Subgroup":"Batteries & Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Midwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":85,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":8,
      "Total_Days_Identified_Through_Closing":98,
      "Total_Days_Identified_Through_Qualified":98,
      "Opportunity_Amount_USD":92024,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.310591,
      "Ratio_Days_Qualified_To_Total_Days":0.689409,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4605474,
      "Supplies_Subgroup":"Motorcycle Parts",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Pacific",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":91,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":7,
      "Total_Days_Identified_Through_Closing":92,
      "Total_Days_Identified_Through_Qualified":92,
      "Opportunity_Amount_USD":8000,
      "Client_Size_By_Revenue":2,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.411509,
      "Ratio_Days_Qualified_To_Total_Days":0.588491,
      "Deal_Size_Category":1
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4618906,
      "Supplies_Subgroup":"Replacement Parts",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":62,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":4,
      "Total_Days_Identified_Through_Closing":71,
      "Total_Days_Identified_Through_Qualified":71,
      "Opportunity_Amount_USD":0,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"None",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":1,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":1
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4622214,
      "Supplies_Subgroup":"Replacement Parts",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":84,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":3,
      "Total_Days_Identified_Through_Closing":99,
      "Total_Days_Identified_Through_Qualified":99,
      "Opportunity_Amount_USD":60000,
      "Client_Size_By_Revenue":4,
      "Client_Size_By_Employee_Count":4,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.907614,
      "Ratio_Days_Validated_To_Total_Days":0.092386,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4625636,
      "Supplies_Subgroup":"Batteries & Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":64,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":7,
      "Total_Days_Identified_Through_Closing":48,
      "Total_Days_Identified_Through_Qualified":48,
      "Opportunity_Amount_USD":120481,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.46473,
      "Ratio_Days_Qualified_To_Total_Days":0.53527,
      "Deal_Size_Category":5
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4642415,
      "Supplies_Subgroup":"Garage & Car Care",
      "Supplies_Group":"Car Accessories",
      "Region":"Midwest",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":24,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":3,
      "Total_Days_Identified_Through_Closing":76,
      "Total_Days_Identified_Through_Qualified":76,
      "Opportunity_Amount_USD":14800,
      "Client_Size_By_Revenue":2,
      "Client_Size_By_Employee_Count":2,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":1,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":2
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4664627,
      "Supplies_Subgroup":"Batteries & Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Other",
      "Elapsed_Days_In_Sales_Stage":88,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":2,
      "Total_Days_Identified_Through_Closing":93,
      "Total_Days_Identified_Through_Qualified":93,
      "Opportunity_Amount_USD":400000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":1,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":6
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4671852,
      "Supplies_Subgroup":"Garage & Car Care",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":16,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":5,
      "Total_Days_Identified_Through_Closing":149,
      "Total_Days_Identified_Through_Qualified":149,
      "Opportunity_Amount_USD":62005,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":1,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4697381,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Midwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":77,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":7,
      "Total_Days_Identified_Through_Closing":102,
      "Total_Days_Identified_Through_Qualified":102,
      "Opportunity_Amount_USD":200000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.863992,
      "Ratio_Days_Qualified_To_Total_Days":0.136008,
      "Deal_Size_Category":5
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4716222,
      "Supplies_Subgroup":"Towing & Hitches",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":44,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":3,
      "Total_Days_Identified_Through_Closing":135,
      "Total_Days_Identified_Through_Qualified":135,
      "Opportunity_Amount_USD":36144,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"None",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.148258,
      "Ratio_Days_Qualified_To_Total_Days":0.851742,
      "Deal_Size_Category":3
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4716249,
      "Supplies_Subgroup":"Towing & Hitches",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":65,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":2,
      "Total_Days_Identified_Through_Closing":114,
      "Total_Days_Identified_Through_Qualified":114,
      "Opportunity_Amount_USD":120481,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":2,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"None",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":1,
      "Deal_Size_Category":5
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4725852,
      "Supplies_Subgroup":"Batteries & Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":84,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":3,
      "Total_Days_Identified_Through_Closing":95,
      "Total_Days_Identified_Through_Qualified":95,
      "Opportunity_Amount_USD":55000,
      "Client_Size_By_Revenue":3,
      "Client_Size_By_Employee_Count":2,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.697257,
      "Ratio_Days_Validated_To_Total_Days":0.302743,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4746662,
      "Supplies_Subgroup":"Garage & Car Care",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":16,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":5,
      "Total_Days_Identified_Through_Closing":145,
      "Total_Days_Identified_Through_Qualified":145,
      "Opportunity_Amount_USD":77507,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":1,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4768009,
      "Supplies_Subgroup":"Garage & Car Care",
      "Supplies_Group":"Car Accessories",
      "Region":"Midwest",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":81,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":6,
      "Total_Days_Identified_Through_Closing":52,
      "Total_Days_Identified_Through_Qualified":52,
      "Opportunity_Amount_USD":1477,
      "Client_Size_By_Revenue":2,
      "Client_Size_By_Employee_Count":2,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.614943,
      "Ratio_Days_Validated_To_Total_Days":0.385057,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":1
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4783340,
      "Supplies_Subgroup":"Towing & Hitches",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Other",
      "Elapsed_Days_In_Sales_Stage":77,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":6,
      "Total_Days_Identified_Through_Closing":96,
      "Total_Days_Identified_Through_Qualified":96,
      "Opportunity_Amount_USD":38554,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":5,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":0.268063,
      "Ratio_Days_Validated_To_Total_Days":0.731937,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":3
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4784063,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Midwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":74,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":7,
      "Total_Days_Identified_Through_Closing":102,
      "Total_Days_Identified_Through_Qualified":102,
      "Opportunity_Amount_USD":300000,
      "Client_Size_By_Revenue":4,
      "Client_Size_By_Employee_Count":2,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":0.245079,
      "Ratio_Days_Validated_To_Total_Days":0.67126,
      "Ratio_Days_Qualified_To_Total_Days":0.083661,
      "Deal_Size_Category":6
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4784411,
      "Supplies_Subgroup":"Replacement Parts",
      "Supplies_Group":"Car Accessories",
      "Region":"Midwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":90,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":8,
      "Total_Days_Identified_Through_Closing":68,
      "Total_Days_Identified_Through_Qualified":68,
      "Opportunity_Amount_USD":41000,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":4,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.39645,
      "Ratio_Days_Validated_To_Total_Days":0.553254,
      "Ratio_Days_Qualified_To_Total_Days":0.050296,
      "Deal_Size_Category":3
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4798697,
      "Supplies_Subgroup":"Garage & Car Care",
      "Supplies_Group":"Car Accessories",
      "Region":"Midwest",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":7,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":10,
      "Total_Days_Identified_Through_Closing":90,
      "Total_Days_Identified_Through_Qualified":90,
      "Opportunity_Amount_USD":20000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.773438,
      "Ratio_Days_Qualified_To_Total_Days":0.226562,
      "Deal_Size_Category":2
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4806566,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Pacific",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":24,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":8,
      "Total_Days_Identified_Through_Closing":73,
      "Total_Days_Identified_Through_Qualified":65,
      "Opportunity_Amount_USD":30000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.142661,
      "Ratio_Days_Qualified_To_Total_Days":0.742112,
      "Deal_Size_Category":3
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4806813,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Pacific",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":70,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":10,
      "Total_Days_Identified_Through_Closing":106,
      "Total_Days_Identified_Through_Qualified":106,
      "Opportunity_Amount_USD":462000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Known",
      "Ratio_Days_Identified_To_Total_Days":0.130806,
      "Ratio_Days_Validated_To_Total_Days":0.267299,
      "Ratio_Days_Qualified_To_Total_Days":0.601896,
      "Deal_Size_Category":6
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4815830,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":89,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":7,
      "Total_Days_Identified_Through_Closing":61,
      "Total_Days_Identified_Through_Qualified":61,
      "Opportunity_Amount_USD":697674,
      "Client_Size_By_Revenue":5,
      "Client_Size_By_Employee_Count":2,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.130719,
      "Ratio_Days_Validated_To_Total_Days":0.767974,
      "Ratio_Days_Qualified_To_Total_Days":0.101307,
      "Deal_Size_Category":7
    }
  },
  {
    "attributes":{
      "Opportunity_Number":4836120,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Midwest",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":24,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":9,
      "Total_Days_Identified_Through_Closing":18,
      "Total_Days_Identified_Through_Qualified":17,
      "Opportunity_Amount_USD":100000,
      "Client_Size_By_Revenue":4,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0.61236,
      "Ratio_Days_Qualified_To_Total_Days":0.365169,
      "Deal_Size_Category":5
    }
  },
  {
    "attributes":{
      "Opportunity_Number":5135671,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Northwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":69,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":5,
      "Total_Days_Identified_Through_Closing":92,
      "Total_Days_Identified_Through_Qualified":92,
      "Opportunity_Amount_USD":500000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":2,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0.035753,
      "Ratio_Days_Validated_To_Total_Days":0.448537,
      "Ratio_Days_Qualified_To_Total_Days":0.51571,
      "Deal_Size_Category":7
    }
  },
  {
    "attributes":{
      "Opportunity_Number":10081102,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Southeast",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":0,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":2,
      "Total_Days_Identified_Through_Closing":0,
      "Total_Days_Identified_Through_Qualified":0,
      "Opportunity_Amount_USD":59000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":10081854,
      "Supplies_Subgroup":"Garage & Car Care",
      "Supplies_Group":"Car Accessories",
      "Region":"Northeast",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":0,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":1,
      "Total_Days_Identified_Through_Closing":0,
      "Total_Days_Identified_Through_Qualified":0,
      "Opportunity_Amount_USD":17000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":2
    }
  },
  {
    "attributes":{
      "Opportunity_Number":10082531,
      "Supplies_Subgroup":"Motorcycle Parts",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Southeast",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":0,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":1,
      "Total_Days_Identified_Through_Closing":0,
      "Total_Days_Identified_Through_Qualified":0,
      "Opportunity_Amount_USD":12000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":2
    }
  },
  {
    "attributes":{
      "Opportunity_Number":10083432,
      "Supplies_Subgroup":"Motorcycle Parts",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Southwest",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":0,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":1,
      "Total_Days_Identified_Through_Closing":0,
      "Total_Days_Identified_Through_Qualified":0,
      "Opportunity_Amount_USD":291,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":1
    }
  },
  {
    "attributes":{
      "Opportunity_Number":10085039,
      "Supplies_Subgroup":"Interior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Southeast",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":0,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":1,
      "Total_Days_Identified_Through_Closing":0,
      "Total_Days_Identified_Through_Qualified":0,
      "Opportunity_Amount_USD":5376,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":1
    }
  },
  {
    "attributes":{
      "Opportunity_Number":10085764,
      "Supplies_Subgroup":"Garage & Car Care",
      "Supplies_Group":"Car Accessories",
      "Region":"Mid-Atlantic",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":0,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":1,
      "Total_Days_Identified_Through_Closing":0,
      "Total_Days_Identified_Through_Qualified":0,
      "Opportunity_Amount_USD":57982,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":10086420,
      "Supplies_Subgroup":"Batteries & Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Southwest",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":0,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":1,
      "Total_Days_Identified_Through_Closing":0,
      "Total_Days_Identified_Through_Qualified":0,
      "Opportunity_Amount_USD":18000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":2
    }
  },
  {
    "attributes":{
      "Opportunity_Number":10089917,
      "Supplies_Subgroup":"Garage & Car Care",
      "Supplies_Group":"Car Accessories",
      "Region":"Southeast",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":0,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":1,
      "Total_Days_Identified_Through_Closing":0,
      "Total_Days_Identified_Through_Qualified":0,
      "Opportunity_Amount_USD":22000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":3,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":2
    }
  },
  {
    "attributes":{
      "Opportunity_Number":10089932,
      "Supplies_Subgroup":"Batteries & Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Southeast",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":0,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":2,
      "Total_Days_Identified_Through_Closing":0,
      "Total_Days_Identified_Through_Qualified":0,
      "Opportunity_Amount_USD":250000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":3,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":6
    }
  },
  {
    "attributes":{
      "Opportunity_Number":10089961,
      "Supplies_Subgroup":"Shelters & RV",
      "Supplies_Group":"Performance & Non-auto",
      "Region":"Northeast",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":0,
      "Opportunity_Result":"Won",
      "Sales_Stage_Change_Count":1,
      "Total_Days_Identified_Through_Closing":0,
      "Total_Days_Identified_Through_Qualified":0,
      "Opportunity_Amount_USD":180000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":5
    }
  },
  {
    "attributes":{
      "Opportunity_Number":10090145,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Southeast",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":0,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":2,
      "Total_Days_Identified_Through_Closing":0,
      "Total_Days_Identified_Through_Qualified":0,
      "Opportunity_Amount_USD":90000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":4
    }
  },
  {
    "attributes":{
      "Opportunity_Number":10090430,
      "Supplies_Subgroup":"Exterior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Southeast",
      "Route_To_Market":"Fields Sales",
      "Elapsed_Days_In_Sales_Stage":0,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":2,
      "Total_Days_Identified_Through_Closing":0,
      "Total_Days_Identified_Through_Qualified":0,
      "Opportunity_Amount_USD":120000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":1,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":5
    }
  },
  {
    "attributes":{
      "Opportunity_Number":10094255,
      "Supplies_Subgroup":"Interior Accessories",
      "Supplies_Group":"Car Accessories",
      "Region":"Mid-Atlantic",
      "Route_To_Market":"Reseller",
      "Elapsed_Days_In_Sales_Stage":0,
      "Opportunity_Result":"Loss",
      "Sales_Stage_Change_Count":1,
      "Total_Days_Identified_Through_Closing":0,
      "Total_Days_Identified_Through_Qualified":0,
      "Opportunity_Amount_USD":90000,
      "Client_Size_By_Revenue":1,
      "Client_Size_By_Employee_Count":1,
      "Revenue_From_Client_Past_Two_Years":0,
      "Competitor_Type":"Unknown",
      "Ratio_Days_Identified_To_Total_Days":0,
      "Ratio_Days_Validated_To_Total_Days":0,
      "Ratio_Days_Qualified_To_Total_Days":0,
      "Deal_Size_Category":4
    }
  }
]